_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.2
            "6": 4.47.1
            "8":
                - 1
                - 5
            "12": 0.19.2
            "13": linux-x86_64
architecture:
    value: |-
        classifierModel(
          (part_number_emb): Linear(in_features=1211, out_features=768, bias=False)
          (price_adapter): Linear(in_features=1, out_features=768, bias=False)
          (cluster_emb): Linear(in_features=102, out_features=768, bias=False)
          (norm1): BatchNorm1d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (linear1): Linear(in_features=768, out_features=384, bias=True)
          (dropout1): Dropout(p=0.5, inplace=False)
          (norm2): BatchNorm1d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (linear2): Linear(in_features=384, out_features=100, bias=True)
          (dropout2): Dropout(p=0.5, inplace=False)
        )
epochs:
    value: 100
learning_rate:
    value: 0.001
loss_function:
    value: CrossEntropyLoss
optimizer:
    value: Adam
